# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06c7171b024f5e8b40c782bd2ab1aabfbefe6ee5bc3fddfa38544d7174a5eee5bd33f4d295fe7712bf50370ca5924505cd89c09feb3b988095dab11da6e2bbf2

test:
  secret_key_base: f005dcd1f9e686c9d76933cb9744dc87fb3e4f6b00adf976c3c4d6aa88f062b41263c0ce2cdbb0c1888607384e7dda18855d51e7964b4a8e539bf7ebdc0873d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
